"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { InterviewDetail as InterviewDetailData } from "@/lib/domain";
import { getAdminInterview } from "./admin-data-client";
import { ProgressBar, StatusBadge } from "./ui";

type Tab = "transcript" | "case" | "rule";
const labels: Record<string, string> = { discovery: "机会发现", judgement: "判断逻辑", action: "行动策略", result: "效果反馈", limitation: "边界条件" };
function profileValue(detail: InterviewDetailData, candidates: string[], fallback: string) { for (const candidate of candidates) { const value = detail.userProfile.profile[candidate]; if (typeof value === "string" && value.trim()) return value; } return fallback; }

export function InterviewDetail({ id }: { id: string }) {
  const [detail, setDetail] = useState<InterviewDetailData | null>(null);
  const [tab, setTab] = useState<Tab>("transcript");
  const [error, setError] = useState("");
  useEffect(() => { let active = true; getAdminInterview(id).then((item) => active && setDetail(item)).catch((reason) => active && setError(reason instanceof Error ? reason.message : "无法读取访谈")); return () => { active = false; }; }, [id]);
  if (error) return <div className="admin-interview-detail"><Link href="/admin/scenarios" className="admin-back-link">← 返回任务</Link><div className="admin-demo-notice" role="alert"><div><strong>无法读取访谈</strong><p>{error}</p></div></div></div>;
  if (!detail) return <div className="admin-interview-detail"><div className="admin-card"><div className="admin-empty-state"><h2>正在读取访谈</h2><p>仅加载所属机构的访谈内容。</p></div></div></div>;
  const name = profileValue(detail, ["姓名", "name"], "匿名参与者");
  const organization = profileValue(detail, ["机构", "organization"], "未填写机构");
  const state = detail.extractionState;
  const coverage = Object.entries(labels).map(([key, label]) => ({ label, value: state[key as keyof typeof state] ? 100 : 0 }));
  return <div className="admin-interview-detail"><Link href={`/admin/scenarios/${detail.scenario.id}`} className="admin-back-link">← 返回任务</Link><header className="admin-interview-hero"><div className="admin-interview-person"><span className="admin-interview-person__avatar">{name.slice(0, 1)}</span><div><div className="admin-interview-person__eyebrow"><span>访谈记录</span><i /> <span>{detail.id}</span></div><h1>{name}</h1><p>{organization} · {detail.scenario.name}</p></div></div><div className="admin-interview-hero__actions"><StatusBadge status={detail.status === "completed" ? "completed" : "processing"} /></div></header><section className="admin-interview-meta"><div><span>访谈状态</span><strong>{detail.status === "completed" ? "已完成" : "进行中"}</strong></div><div><span>消息数量</span><strong>{detail.messages.length}</strong></div><div><span>案例状态</span><strong>{detail.generationStatus === "failed" ? "生成失败" : detail.extractedCase ? "待审核" : "尚未生成"}</strong></div></section><div className="admin-interview-notice">该访谈仅对所属机构管理员可见；AI 产出均为待审核草稿，不能直接作为正式业务规则。</div><nav className="admin-detail-tabs admin-interview-tabs">{([{ id: "transcript", label: "对话记录" }, { id: "case", label: "个人案例" }, { id: "rule", label: "经验规则" }] as const).map((item) => <button key={item.id} type="button" className={tab === item.id ? "is-current" : undefined} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    {tab === "transcript" ? <section className="admin-interview-layout"><article className="admin-card admin-transcript-card"><div className="admin-card__header"><div><h2>访谈原文</h2><p>文字与经参与者确认的语音转写均保留来源类型。</p></div></div><div className="admin-transcript">{detail.messages.map((message) => <div className={`admin-message admin-message--${message.role}`} key={message.id}><div className="admin-message__avatar">{message.role === "assistant" ? "小萃" : name.slice(0, 1)}</div><div><div><strong>{message.role === "assistant" ? "小萃" : name}</strong><small>{message.messageType === "audio_transcript" ? "语音转写（已确认）" : message.messageType === "text" ? "文字输入" : message.messageType}</small></div><p>{message.content}</p></div></div>)}</div></article><aside className="admin-interview-rail"><article className="admin-card admin-challenge-snapshot"><div className="admin-card__header"><div><h2>挑战案例</h2><p>{detail.challengeCase.source === "ai" ? "AI 模拟 · 待审核" : "预置案例"}</p></div></div><div className="admin-card__body"><h3>{detail.challengeCase.title}</h3><p>{detail.challengeCase.description}</p></div></article><article className="admin-card admin-coverage-rail"><div className="admin-card__header"><div><h2>信息覆盖</h2><p>根据 Agent 当前结构化状态</p></div></div><div className="admin-card__body">{coverage.map((item) => <div className="admin-coverage-rail__item" key={item.label}><div><span>{item.label}</span><strong>{item.value}%</strong></div><ProgressBar value={item.value} /></div>)}</div></article></aside></section> : null}
    {tab === "case" ? <section className="admin-output-document"><article className="admin-output-document__main"><p className="admin-kicker">EXTRACTED CASE / PENDING REVIEW</p>{detail.extractedCase ? <><h2>{detail.extractedCase.title}</h2><div className="admin-output-sections">{(["background", "discovery", "judgement", "action", "result", "limitation"] as const).map((key) => <section key={key}><h3>{({ background: "背景", discovery: "发现", judgement: "判断", action: "行动", result: "结果", limitation: "边界" } as Record<string, string>)[key]}</h3><p>{detail.extractedCase?.[key]}</p></section>)}</div></> : <p>尚未生成个人案例；访谈完成并成功调用案例生成后才会出现。</p>}</article></section> : null}
    {tab === "rule" ? <section className="admin-rule-document">{detail.experienceRules.length ? detail.experienceRules.map((rule) => <article className="admin-output-document__main" key={rule.id}><p className="admin-kicker">EXPERIENCE RULE / PENDING REVIEW</p><h2>候选经验规则</h2><dl className="admin-reference-rule"><div><dt>触发条件</dt><dd>{rule.condition}</dd></div><div><dt>判断逻辑</dt><dd>{rule.judgement}</dd></div><div><dt>推荐动作</dt><dd>{rule.strategy}</dd></div><div className="is-risk"><dt>不适用条件</dt><dd>{rule.limitation}</dd></div></dl></article>) : <article className="admin-card"><div className="admin-empty-state"><h2>尚未生成经验规则</h2><p>规则会随个人案例生成，且必须经过人工审核。</p></div></article>}</section> : null}
  </div>;
}
